# Generated by Django 3.1.1 on 2020-09-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment', '0004_auto_20200920_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcomment',
            name='comment',
            field=models.TextField(max_length=250),
        ),
    ]
