# Generated by Django 3.1.1 on 2020-09-20 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empowerment', '0005_auto_20200920_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocomment',
            old_name='bookId',
            new_name='videoId',
        ),
    ]
